import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import  Footer from "@/components/Footer";
import Tobar from "@/components/Tobar";
import Navbar from "@/components/Navbar";


const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Nike-UI---Free-UI-Kit-(Recreated)-(Community)?",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}
       
>  <Tobar/>
<Navbar/>
{children}
<Footer/>
        

      </body>
    </html>
  );
}
